config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-Autocompletion:
      branch: master
      repo: https://github.com/athenarc/EOSCF-Autocompletion.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-Autocompletion git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-myrtle-caterpillar.sh
        container: qc.acc_lanky-scarlet-olm
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-Autocompletion find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-wheat-worm.sh
        container: qc.doc_woolly-pink-bird
      github.com/athenarc/EOSCF-Autocompletion git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-taupe-caracal.sh
        container: qc.doc_pasty-thistle-jaguar
      github.com/athenarc/EOSCF-Autocompletion markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-lilac-gopher.sh
        container: qc.doc_droopy-cerulean-sheepdog
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-Autocompletion licensee:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-lemon-budgerigar.sh
        container: qc.lic_skanky-taupe-tarsier
  QC.Met:
    repos:
      github.com/athenarc/EOSCF-Autocompletion cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-charcoal-tarsier.sh
        container: qc.met_scaly-ivory-reindeer
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-Autocompletion bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-violet-avocet.sh
        container: qc.sec_sleazy-grey-gorilla
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-Autocompletion flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-gold-nightingale.sh
        container: qc.sty_bumpy-taupe-fossa
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-Autocompletion get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-chestnut-bullfrog.sh
        container: qc.ver_hazy-indigo-lion
timeout: 5400
